Courtyard\Bundle\ForumBundle\Entity\Board:
    type: entity
    table: forum_board
    repositoryClass: Courtyard\Bundle\ForumBundle\Repository\BoardRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            
        slug:
            type: string