Courtyard\Bundle\ForumBundle\Entity\Topic:
    type: entity
    table: forum_topic
    repositoryClass: Courtyard\Bundle\ForumBundle\Repository\TopicRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string

        datePosted:
            type: datetime

        dateUpdated:
            type: datetime

        status:
            type: integer

        views:
            type: integer

    manyToOne:
        board:
            targetEntity: Courtyard\Bundle\ForumBundle\Entity\Board

        author:
            targetEntity: Courtyard\Forum\Entity\UserInterface

        postFirst:
            targetEntity: Courtyard\Bundle\ForumBundle\Entity\Post
            name: post_first_id
            cascade:
                - persist

        postLast:
            targetEntity: Courtyard\Bundle\ForumBundle\Entity\Post
            name: post_last_id

    oneToMany:
        posts:
            targetEntity: Courtyard\Bundle\ForumBundle\Entity\Post
            mappedBy: topic