Courtyard\Bundle\ForumBundle\Entity\Topic:
    type: mappedSuperclass
    table: forum_topic
    repositoryClass: Courtyard\Bundle\ForumBundle\Repository\TopicRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string

        slug:
            type: string

        datePosted:
            type: datetime

        dateUpdated:
            type: datetime

        status:
            type: integer

        views:
            type: integer