forum_index:
    pattern: /
    defaults: { _controller: courtyard_forum.controller.board:indexAction }

forum_view:
    pattern: /{boardSlug}
    defaults: { _controller: courtyard_forum.controller.board:viewAction }

forum_topic_create:
    pattern: /{boardSlug}/create
    defaults: { _controller: courtyard_forum.controller.topic:postAction }

forum_topic_view:
    pattern: /{boardSlug}/{topicId}
    defaults: { _controller: courtyard_forum.controller.topic:viewAction }


forum_post_view:
    pattern: /posts/{id}
    defaults: { _controller: courtyard_forum.controller.post:viewAction }
    
forum_reply:
    pattern: /{boardSlug}/{topicId}/reply
    defaults: { _controller: courtyard_forum.controller.post:replyAction }

forum_reply_inline:
    pattern: /{boardSlug}/{topicId}/reply-inline
    defaults: { _controller: courtyard_forum.controller.post:replyInlineAction }

#forum_post_reply:
#forum_post_edit: