forum_index:
    pattern: /
    defaults: { _controller: courtyard_forum.controller.board:indexAction }

forum_view:
    pattern: /{slug}
    defaults: { _controller: courtyard_forum.controller.board:viewAction }

forum_topic_create:
    pattern: /{slug}/create
    defaults: { _controller: courtyard_forum.controller.topic:postAction }

forum_topic_view:
    pattern: /{board.slug}/{topic.id}
    defaults: { _controller: courtyard_forum.controller.topic:viewAction }


forum_post_view:
    pattern: /posts/{id}
    defaults: { _controller: courtyard_forum.controller.post:viewAction }
    
forum_reply:
    pattern: /posts/reply/{id}
    defaults: { _controller: courtyard_forum.controller.post:replyAction }

forum_reply_inline:
    pattern: /posts/reply-inline/{id}
    defaults: { _controller: courtyard_forum.controller.post:replyInlineAction }

#forum_post_reply:
#forum_post_edit: