parameters:
    courtyard_forum.router.slug_inflector_class: Courtyard\Forum\Util\Inflector\SlugInflector

services:
    courtyard_forum.manager:
        class: Courtyard\Forum\Manager\TransactionalManager
        arguments:
            - @courtyard_forum.manager.transaction_dispatcher

    courtyard_forum.manager.transaction_dispatcher:
        class: Courtyard\Forum\Manager\Transaction\TransactionDispatcher
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
    

    courtyard_forum.manager.board:
        parent: courtyard_forum.manager
        class: Courtyard\Forum\Manager\BoardManager
        calls:
            - [ setClass, [ %courtyard_forum.entity_class.board% ]]

    courtyard_forum.manager.topic:
        parent: courtyard_forum.manager
        class: Courtyard\Forum\Manager\TopicManager
        calls:
            - [ setClass, [ %courtyard_forum.entity_class.topic% ]]

    courtyard_forum.manager.post:
        parent: courtyard_forum.manager
        class: Courtyard\Forum\Manager\PostManager
        calls:
            - [ setClass, [ %courtyard_forum.entity_class.post% ] ]

    courtyard_forum.listener.view:
        class: Courtyard\Bundle\ForumBundle\EventListener\ConvertResponse
        arguments:
            - @event_dispatcher
            - @templating
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    courtyard_forum.listener.author:
        class: Courtyard\Bundle\ForumBundle\EventListener\SetAuthor
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_subscriber }

    courtyard_forum.listener.timestamps:
        class: Courtyard\Bundle\ForumBundle\EventListener\SetTimestamps
        tags:
            - { name: kernel.event_subscriber }

    courtyard_forum.listener.slugify:
        class: Courtyard\Bundle\ForumBundle\EventListener\SetSlug
        arguments:
            - %courtyard_forum.router.slug_inflector_class%
        tags:
            - { name: kernel.event_subscriber }

    courtyard_forum.listener.lastpost:
        class: Courtyard\Bundle\ForumBundle\EventListener\UpdateLastPost
        arguments:
            - @courtyard_forum.repository.post
        tags:
            - { name: kernel.event_subscriber }

    courtyard_forum.listener.quickreply:
        class: Courtyard\Bundle\ForumBundle\EventListener\AddQuickReply
        arguments:
            - @form.factory
            - @courtyard_forum.manager.post
        tags:
            - { name: kernel.event_listener, event: view.topic, method: onTopicView }

    courtyard_forum.rebuild.postnumbers:
        class: Courtyard\Forum\Manager\DataRebuild\Post\RenumberPosts
        arguments:
            - @courtyard_forum.repository.post

    courtyard_forum.listener.rebuild.postnumbers:
        class: Courtyard\Bundle\ForumBundle\EventListener\RenumberPosts
        arguments:
            - @courtyard_forum.rebuild.postnumbers
        tags:
            - { name: kernel.event_listener, event: post.delete.post, method: onPostDelete }

    courtyard_forum.router:
        class: Courtyard\Forum\Router\ForumUrlGenerator
        arguments:
            - @router
            - %courtyard_forum.pagination.posts_per_page%
            - %courtyard_forum.pagination.topics_per_page%


    courtyard_forum.router.canonical_rediector:
        class: Courtyard\Bundle\ForumBundle\EventListener\RedirectCanonicalUrls
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest, priority: -5000 }

    courtyard_forum.listener.breadcrumb:
        class: Courtyard\Bundle\ForumBundle\EventListener\DefineBreadcrumbs
        arguments:
            - @white_october_breadcrumbs
            - @courtyard_forum.router
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest, priority: -5000 }

    courtyard_forum.router.twig.extension:
        class: Courtyard\Bundle\ForumBundle\Twig\Extension\RoutingExtension
        arguments:
            - @courtyard_forum.router
        tags:
            - { name: twig.extension }