parameters:

services:
    courtyard_forum.manager:
        class: Courtyard\Forum\Manager\AbstractManager
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    courtyard_forum.manager.topic:
        parent: courtyard_forum.manager
        class: Courtyard\Forum\Manager\TopicManager
        calls:
            - [ setClass, [ %courtyard_forum.entity_class.topic% ]]

    courtyard_forum.manager.post:
        parent: courtyard_forum.manager
        class: Courtyard\Forum\Manager\PostManager
        calls:
            - [ setClass, [ %courtyard_forum.entity_class.post% ] ]

    courtyard_forum.listener.timestamps:
        class: Courtyard\Bundle\ForumBundle\EventListener\SetTimestamps
        tags:
            - { name: kernel.event_subscriber }